version: "2.4"
services:
  wgcf:
    image: neilpang/wgcf-docker:latest
    volumes:
      - ./wgcf:/wgcf
      - /lib/modules:/lib/modules
    privileged: true
    ports:
      - "127.0.0.1:30000:30000/tcp"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    cap_add:
      - NET_ADMIN

  proxy-pool:
    build:
      context: .
    network_mode: "service:wgcf"
    depends_on:
      - wgcf
